# -*- coding: utf-8 -*-
"""
convert_geojson_to_js.py

作用：
    将 assets/maps/china.json 转换为 js/china_map.js。

为什么需要：
    如果网页里使用 fetch("assets/maps/china.json")，双击 index.html 打开时，
    浏览器通常会因为本地文件安全限制而禁止读取 JSON。

    本脚本会把 china.json 直接转换成 JS 变量：
        const chinaJson = {...};

    这样 index.html 可以直接双击打开，不需要 python -m http.server。

输入：
    assets/maps/china.json

输出：
    js/china_map.js

运行：
    python convert_geojson_to_js.py

index.html 中推荐脚本顺序：
    <script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
    <script src="js/china_map.js"></script>
    <script src="js/city_data.js"></script>
    <script src="js/script.js"></script>
"""

from pathlib import Path
import json


BASE_DIR = Path(__file__).resolve().parent

INPUT_PATH = BASE_DIR / "assets" / "maps" / "china.json"
OUTPUT_DIR = BASE_DIR / "js"
OUTPUT_PATH = OUTPUT_DIR / "china_map.js"


def main():
    if not INPUT_PATH.exists():
        raise FileNotFoundError(
            f"找不到输入文件：{INPUT_PATH}\n"
            "请确认 china.json 已经放到 assets/maps/china.json"
        )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print(f"读取：{INPUT_PATH}")

    with INPUT_PATH.open("r", encoding="utf-8") as f:
        geojson = json.load(f)

    if not isinstance(geojson, dict):
        raise ValueError("china.json 格式异常：根对象不是 JSON object。")

    if geojson.get("type") != "FeatureCollection":
        print("警告：china.json 的 type 不是 FeatureCollection，但仍会继续转换。")

    if "features" not in geojson:
        print("警告：china.json 中没有 features 字段，请确认这是否是有效 GeoJSON。")

    js_text = (
        "/* Auto-generated by convert_geojson_to_js.py. Do not edit manually. */\n"
        "const chinaJson = "
        + json.dumps(geojson, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )

    OUTPUT_PATH.write_text(js_text, encoding="utf-8")

    input_size = INPUT_PATH.stat().st_size / 1024 / 1024
    output_size = OUTPUT_PATH.stat().st_size / 1024 / 1024

    print(f"已生成：{OUTPUT_PATH}")
    print(f"原始 JSON 大小：{input_size:.2f} MB")
    print(f"输出 JS 大小：{output_size:.2f} MB")
    print("\n下一步：")
    print("1. 在 index.html 中加入：")
    print('   <script src="js/china_map.js"></script>')
    print("2. 并确保顺序为：")
    print('   <script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>')
    print('   <script src="js/china_map.js"></script>')
    print('   <script src="js/city_data.js"></script>')
    print('   <script src="js/script.js"></script>')


if __name__ == "__main__":
    main()
